CFLAGS=-Wall -g

build-1:
	gcc problem1.c -o 1
run-1: build-1
	./1

build-2:
	gcc problem2.c -o 2
run-2: build-2
	./2

build-3:
	gcc problem3.c -o 3
run-3: build-3
	./3

build-4:
	gcc problem4.c -o 4
run-4: build-4
	./4

build-5:
	gcc problem5.c -o 5
run-5: build-5
	./5

build-6:
	gcc problem6.c -o 6
run-4: build-6
	./6

build-7:
	gcc problem7.c -o 7
run-7: build-7
	./7

build-8:
	gcc problem8.c -o 8
run-8: build-8
	./8

build-9:
	gcc problem9.c -o 9
run-9: build-9
	./9

build-10:
	gcc problem10.c -o 10
run-10: build-10
	./10

build-11:
	gcc problem11.c -o 11
run-11: build-11
	./11

build-12:
	gcc problem12.c -o 12
run-12: build-12
	./12

clean:
	rm 1 2 3 4
